# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-05-18 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='filtermodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('dept', models.CharField(max_length=200)),
                ('date', models.DateField(max_length=200)),
            ],
        ),
    ]
